//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class COM_BattlePositionWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(COM_BattlePosition), typeof(System.Object));
		L.RegFunction("Serialize", Serialize);
		L.RegFunction("Deserialize", Deserialize);
		L.RegFunction("New", _CreateCOM_BattlePosition);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("InstId", get_InstId, set_InstId);
		L.RegVar("Position", get_Position, set_Position);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateCOM_BattlePosition(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				COM_BattlePosition obj = new COM_BattlePosition();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: COM_BattlePosition.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Serialize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			COM_BattlePosition obj = (COM_BattlePosition)ToLua.CheckObject(L, 1, typeof(COM_BattlePosition));
			IWriter arg0 = (IWriter)ToLua.CheckObject(L, 2, typeof(IWriter));
			obj.Serialize(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Deserialize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			COM_BattlePosition obj = (COM_BattlePosition)ToLua.CheckObject(L, 1, typeof(COM_BattlePosition));
			IReader arg0 = (IReader)ToLua.CheckObject(L, 2, typeof(IReader));
			bool o = obj.Deserialize(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InstId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			COM_BattlePosition obj = (COM_BattlePosition)o;
			long ret = obj.InstId;
			LuaDLL.tolua_pushint64(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index InstId on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Position(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			COM_BattlePosition obj = (COM_BattlePosition)o;
			int ret = obj.Position;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Position on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_InstId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			COM_BattlePosition obj = (COM_BattlePosition)o;
			long arg0 = LuaDLL.tolua_checkint64(L, 2);
			obj.InstId = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index InstId on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Position(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			COM_BattlePosition obj = (COM_BattlePosition)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.Position = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Position on a nil value" : e.Message);
		}
	}
}

