sys.loadfile("common.lua")
sys.loadfile("test.lua")
sys.loadfile("skill1.lua")
sys.loadfile("skill2.lua")
sys.loadfile("skill3.lua")
sys.loadfile("skill4.lua")
sys.loadfile("skill5.lua")
sys.loadfile("skill6.lua")